version: "3.9"

services:
  uss_main:
    build: .
    image: themepark_analysis_main
    container_name: uss_main_container
    volumes:
      - .:/app
    working_dir: /app
    command: python src/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

  uss_a:
    build: .
    image: themepark_analysis_a
    container_name: uss_a_container
    volumes:
      - .:/app
    working_dir: /app
    command: python src/subgroup_a/main_A.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

  uss_b:
    build: .
    image: themepark_analysis_b
    container_name: uss_b_container
    volumes:
      - .:/app
    working_dir: /app
    command: python src/subgroup_b/main_B.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
